[project]
name = "sbf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "cachetools>=6.2.1",
    "fastapi>=0.119.0",
    "httpx>=0.28.1",
    "toml>=0.10.2",
    "uvicorn>=0.37.0",
]
